### ISSUE TITLE
[description]

### ISSUE THREAD

**Issue by cskimpel** [SoftwareEngineeringToolDemos/FSE-2014-Critics#1]
No Description at the top of this page.
Add "An interactive code review tool for searching and inspecting systematic changes" to the description.

**Comment by cskimpel** [comment]
Added a description to my fork and created a pull request to add it when approved.

**Comment by cskimpel** [comment]
Added a description to my fork and created a pull request to add it when approved.
Reopened - Closed in error.

**Comment by vinay92** [comment]
Updated the project description.
